// <auto-generated />
namespace FashionGo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new98 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new98));
        
        string IMigrationMetadata.Id
        {
            get { return "201608081717562_new9-8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
